version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    networks:
      - proxy
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_VENDOR=${DB_VENDOR}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${SA_PASSWORD}
      - DB_ADDR=${DB_ADDR}
      - DB_DATABASE=${DB_DATABASE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak-dev.duckdns.org`)"
      - "traefik.http.routers.keycloak.service=keycloak"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
