version: '3'

services:
    datacredito:
        image: motorcredito.azurecr.io/datacredito:v1
        networks:
          - proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.datacredito.rule=Host(`datacredito.duckdns.org`)"
          - "traefik.http.routers.datacredito.service=datacredito"
          - "traefik.http.routers.datacredito.entrypoints=web"
          - "traefik.http.services.datacredito.loadbalancer.server.port=44348"

networks:
    proxy:
        external: true
